# Form implementation generated from reading ui file 'anadir_host.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddHost(object):
    def setupUi(self, AddHost):
        AddHost.setObjectName("AddHost")
        AddHost.resize(417, 409)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddHost)
        self.buttonBox.setGeometry(QtCore.QRect(30, 370, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.AddHost_2 = QtWidgets.QLabel(parent=AddHost)
        self.AddHost_2.setGeometry(QtCore.QRect(20, 20, 51, 31))
        self.AddHost_2.setObjectName("AddHost_2")
        self.le_host = QtWidgets.QLineEdit(parent=AddHost)
        self.le_host.setGeometry(QtCore.QRect(20, 60, 361, 41))
        self.le_host.setObjectName("le_host")
        self.Opciones = QtWidgets.QGroupBox(parent=AddHost)
        self.Opciones.setGeometry(QtCore.QRect(20, 120, 361, 241))
        self.Opciones.setObjectName("Opciones")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.Opciones)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 341, 206))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.insecure = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.insecure.setObjectName("insecure")
        self.gridLayout_3.addWidget(self.insecure, 4, 1, 1, 1)
        self.root_squash = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.root_squash.setObjectName("root_squash")
        self.gridLayout_3.addWidget(self.root_squash, 2, 1, 1, 1)
        self.ro = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.ro.setObjectName("ro")
        self.gridLayout_3.addWidget(self.ro, 0, 1, 1, 1)
        self.sync = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.sync.setObjectName("sync")
        self.gridLayout_3.addWidget(self.sync, 1, 0, 1, 1)
        self.no_root_squash = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.no_root_squash.setObjectName("no_root_squash")
        self.gridLayout_3.addWidget(self.no_root_squash, 2, 0, 1, 1)
        self.no_subtree_check = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.no_subtree_check.setObjectName("no_subtree_check")
        self.gridLayout_3.addWidget(self.no_subtree_check, 3, 1, 1, 1)
        self.subtree_check = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.subtree_check.setObjectName("subtree_check")
        self.gridLayout_3.addWidget(self.subtree_check, 4, 0, 1, 1)
        self.async = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.async.setObjectName("async")
        self.gridLayout_3.addWidget(self.async, 1, 1, 1, 1)
        self.all_squash = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.all_squash.setObjectName("all_squash")
        self.gridLayout_3.addWidget(self.all_squash, 3, 0, 1, 1)
        self.anonuid = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.anonuid.setObjectName("anonuid")
        self.gridLayout_3.addWidget(self.anonuid, 5, 1, 1, 1)
        self.rw = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.rw.setObjectName("rw")
        self.gridLayout_3.addWidget(self.rw, 0, 0, 1, 1)
        self.secure = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.secure.setObjectName("secure")
        self.gridLayout_3.addWidget(self.secure, 5, 0, 1, 1)
        self.anongid = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.anongid.setObjectName("anongid")
        self.gridLayout_3.addWidget(self.anongid, 6, 0, 1, 1)

        self.retranslateUi(AddHost)
        self.buttonBox.accepted.connect(AddHost.accept) # type: ignore
        self.buttonBox.rejected.connect(AddHost.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddHost)

    def retranslateUi(self, AddHost):
        _translate = QtCore.QCoreApplication.translate
        AddHost.setWindowTitle(_translate("AddHost", "Dialog"))
        self.AddHost_2.setText(_translate("AddHost", "Host:"))
        self.Opciones.setTitle(_translate("AddHost", "Opciones"))
        self.insecure.setText(_translate("AddHost", "insecure"))
        self.root_squash.setText(_translate("AddHost", "root_squash"))
        self.ro.setText(_translate("AddHost", "ro"))
        self.sync.setText(_translate("AddHost", "sync"))
        self.no_root_squash.setText(_translate("AddHost", "no_root_squash"))
        self.no_subtree_check.setText(_translate("AddHost", "no_subtree_check"))
        self.subtree_check.setText(_translate("AddHost", "subtree_check"))
        self.async.setText(_translate("AddHost", "async"))
        self.all_squash.setText(_translate("AddHost", "all_squash"))
        self.anonuid.setText(_translate("AddHost", "anonuid"))
        self.rw.setText(_translate("AddHost", "rw"))
        self.secure.setText(_translate("AddHost", "secure"))
        self.anongid.setText(_translate("AddHost", "anongid"))
